import 'package:flutter/material.dart';
import 'package:qs_app/components/mcqs_content_box.dart';

class OtsEnglishContentScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('OTS English'),
      ),
      body: SingleChildScrollView(
        child: Padding(
          padding: EdgeInsets.all(20.0),
          child: Column(
            children: [

              McqsContentBox(
                question: ' The king could only be cured by the ______ of a person endued with certain qualities?',
                option1: 'Blood',
                option2: 'Liver',
                option3: ' Bile',
                option4: 'Kidney',
                option5: 'None of these',
                correctOption: 'c',
              ),
              McqsContentBox(
                question: ' Where did the woman work?',
                option1: 'Office',
                option2: ' College ',
                option3: ' Hotel ',
                option4: ' Beauty shop',
                option5: 'None of these',
                correctOption: 'd',
              ),
              McqsContentBox(
                question: ' The name of Harry Bittering’s wife was?',
                option1: 'Cora',
                option2: 'Della ',
                option3: 'Laura',
                option4: 'Norma',
                option5: 'None of these',
                correctOption: 'a',
              ),
              McqsContentBox(
                question: ' The girl ______ with the doll when I saw her?',
                option1: ' Played',
                option2: ' Plays',
                option3: ' Is playing',
                option4: ' Was playing',
                option5: 'None of these',
                correctOption: 'd',
              ),
              McqsContentBox(
                question: ' She had magnificent blonde hair, in profusion?',
                option1: ' Diffusion',
                option2: ' Head',
                option3: ' Abundance',
                option4: ' Lesser number',
                option5: 'None of these',
                correctOption: 'c',
              ),
              McqsContentBox(
                question: ' What did Gorgios want to become?',
                option1: ' A clerk',
                option2: ' A court acrobat',
                option3: ' A magistrate',
                option4: ' An inspector',
                option5: 'None of these',
                correctOption: 'b',
              ),
              McqsContentBox(
                question: ' I am sure he ______ the exams?',
                option1: ' Has passed',
                option2: ' Passed',
                option3: ' Is passing',
                option4: ' Will pass',
                option5: 'None of these',
                correctOption: 'd',
              ),
              McqsContentBox(
                question: 'I know and that’s one of your most endearing primitive trails?',
                option1: ' Initial',
                option2: ' Ancient',
                option3: ' Boring',
                option4: ' Modern',
                option5: 'None of these',
                correctOption: 'b',
              ),
              McqsContentBox(
                question: ' The stars ______ in the sky?',
                option1: ' Twinkles',
                option2: ' Will twinkle',
                option3: ' Twinkle',
                option4: ' Has twinkled',
                option5: 'None of these',
                correctOption: 'c',
              ),
              McqsContentBox(
                question: ' That is a primitive assumption that all strangers are hostile?',
                option1: ' Redemption',
                option2: ' Supposition',
                option3: ' Corruption',
                option4: ' Selection',
                option5: 'None of these',
                correctOption: 'b',
              ),
              McqsContentBox(
                question: ' This is dreadful?',
                option1: ' Colorful',
                option2: ' Skillful',
                option3: ' Handful',
                option4: ' Fearful',
                option5: 'None of these',
                correctOption: 'd',
              ),
              McqsContentBox(
                question: ' Haste ______ waste?',
                option1: ' Makes',
                option2: ' Made',
                option3: ' Will make',
                option4: ' Have made',
                option5: 'None of these',
                correctOption: 'a',
              ),
              McqsContentBox(
                question: ' And a time to refrain from embracing?',
                option1: ' Vain',
                option2: ' Gain',
                option3: ' Abstain',
                option4: ' Blame',
                option5: 'None of these',
                correctOption: 'c',
              ),
              McqsContentBox(
                question: ' I hunted all over the town to find it?',
                option1: ' Searched',
                option2: ' Walked',
                option3: ' Wandered',
                option4: ' Roamed',
                option5: 'None of these',
                correctOption: 'a',
              ),
              McqsContentBox(
                question: ' It was raining heavily when I ______ outside?',
                option1: ' Gone',
                option2: ' Went',
                option3: ' Will go',
                option4: ' Had gone',
                option5: 'None of these',
                correctOption: 'b',
              ),
              McqsContentBox(
                question: ' I know and that’s one of your most endearing primitive tracts?',
                option1: ' Pleasing',
                option2: ' Old',
                option3: ' Hateful',
                option4: ' Loveable',
                option5: 'None of these',
                correctOption: 'd',
              ),
              McqsContentBox(
                question: ' A coward ______ many times before his death?',
                option1: ' Died',
                option2: ' Dies',
                option3: ' Is dying',
                option4: ' Has died',
                option5: 'None of these',
                correctOption: 'b',
              ),
              McqsContentBox(
                question: ' My curiosity was aroused?',
                option1: ' Ferocity',
                option2: ' Emotions',
                option3: ' Feelings',
                option4: ' Suspense',
                option5: 'None of these',
                correctOption: 'd',
              ),
              McqsContentBox(
                question: ' We usually ______ to Murree in summer?',
                option1: ' Are going',
                option2: ' Goes',
                option3: ' Went',
                option4: ' Go',
                option5: 'None of these',
                correctOption: 'd',
              ),
              McqsContentBox(
                question: ' Who ordered the slave to be thrown into water?',
                option1: ' The king',
                option2: ' The police',
                option3: ' The sergeant',
                option4: ' The man',
                option5: 'None of these',
                correctOption: 'c',
              ),
              McqsContentBox(
                question: ' Slow and steady ______ the race?',
                option1: ' Has won',
                option2: ' Won',
                option3: ' Will win',
                option4: 'Wins',
                option5: 'None of these',
                correctOption: 'd',
              ),
              McqsContentBox(
                question: ' Miss America, I presume?',
                option1: ' Discover',
                option2: ' Imagine',
                option3: ' Assume',
                option4: ' Think',
                option5: 'None of these',
                correctOption: 'c',
              ),
              McqsContentBox(
                question: ' Ali ______ a letter yesterday?',
                option1: ' Wrote',
                option2: ' Writes',
                option3: ' Has written',
                option4: ' Is writing',
                option5: 'None of these',
                correctOption: 'a',
              ),
              McqsContentBox(
                question: ' We ______ T.V. for two hours?',
                option1: ' Has been watching',
                option2: ' Were watching',
                option3: ' Will watch',
                option4: ' Have been watching',
                option5: 'None of these',
                correctOption: 'd',
              ),
              McqsContentBox(
                question: ' We’re stranded on Mars, forever and ever?',
                option1: ' In a difficult position',
                option2: ' Sent',
                option3: ' Fixed',
                option4: ' Sattled',
                option5: 'None of these',
                correctOption: 'a',
              ),
              McqsContentBox(
                question: ' They ______ a lion yesterday?',
                option1: ' Kills',
                option2: ' Had killed',
                option3: ' Killed',
                option4: ' will kill',
                option5: 'None of these',
                correctOption: 'c',
              ),
              McqsContentBox(
                question: ' Wherever Mr. Hubert went, he met with incredulity?',
                option1: ' Disbelief',
                option2: ' Disability',
                option3: ' Fidelity',
                option4: ' None of these',
                option5: 'None of these',
                correctOption: 'a',
              ),
              McqsContentBox(
                question: ' What is the age of the First Man in the Heat Lightning?',
                option1: ' 30 year',
                option2: ' 20 year',
                option3: ' 35 year',
                option4: ' 25 year',
                option5: 'None of these',
                correctOption: 'c',
              ),
              McqsContentBox(
                question: ' Wearing white for Easter tide?',
                option1: ' Day',
                option2: ' Season',
                option3: ' Month',
                option4: ' Festival',
                option5: 'None of these',
                correctOption: 'b',
              ),
              McqsContentBox(
                question: ' He ______ ten miles daily?',
                option1: ' Is walking',
                option2: ' Walked',
                option3: ' Will walk',
                option4: ' Walks',
                option5: 'None of these',
                correctOption: 'd',
              ),
            ],
          ),
        ),
      ),
    );
  }
}


