import 'package:flutter/material.dart';
import 'package:qs_app/components/mcqs_content_box.dart';

class OtsChemistryContentScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('OTS Chemistry'),
      ),
      body: SingleChildScrollView(
        child: Padding(
          padding: EdgeInsets.all(20.0),
          child: Column(
            children: [


              McqsContentBox(
                question: 'Who presented the idea of sterile surgery for the first time?',
                option1: 'Lamarck',
                option2: 'Sir Alexender Fleming',
                option3: 'Thomas Grill',
                option4: 'Joseph Lister',
                option5: 'None of these',
                correctOption: 'd',
              ),
              McqsContentBox(
                question: 'Which drug belongs to hallucinogens?',
                option1: 'Codeine',
                option2: 'Mescaline',
                option3: 'Heroin',
                option4: 'Morphin',
                option5: 'None of these',
                correctOption: 'b',
              ),
              McqsContentBox(
                question: 'Pathogens contain special proteins called?',
                option1: 'Antiseptics',
                option2: 'Antibodies',
                option3: 'Antigens',
                option4: 'Antibiotics',
                option5: 'None of these',
                correctOption: 'c',
              ),
              McqsContentBox(
                question: 'Psilocin is obtained from?',
                option1: 'Cannabis stive',
                option2: 'Mushroom',
                option3: 'Cannabis indica',
                option4: 'Cactus',
                option5: 'None of these',
                correctOption: 'b',
              ),
              McqsContentBox(
                question: 'Hallucinogen’s effect on the?',
                option1: 'Central Nervous system',
                option2: 'Hypothalamus',
                option3: 'Spinal card',
                option4: 'Sympathetic Nervous system',
                option5: 'None of these',
                correctOption: 'd',
              ),
              McqsContentBox(
                question: 'Which of the following drugs is obtained from plants?',
                option1: 'Opium',
                option2: 'Cephalosporin',
                option3: 'Insulin',
                option4: 'Aspirin',
                option5: 'None of these',
                correctOption: 'a',
              ),
              McqsContentBox(
                question: 'The substances used for the treatment cure, prevention of diagnosis of diseases are called?',
                option1: 'Sedatives',
                option2: 'Narcotics',
                option3: 'Hallucinogens',
                option4: 'Medicinal drugs',
                option5: 'None of these',
                correctOption: 'd',
              ),
              McqsContentBox(
                question: 'Is an Analgesic?',
                option1: 'Aspirin',
                option2: 'Diazepam',
                option3: 'Paracetamol',
                option4: 'Both B and C',
                option5: 'None of these',
                correctOption: 'd',
              ),
              McqsContentBox(
                question: 'The most prescribed medications in modern medicine are?',
                option1: 'Cardiotonic',
                option2: 'Hallucinogens',
                option3: 'Antibiotics',
                option4: 'Sedatives',
                option5: 'None of these',
                correctOption: 'c',
              ),
              McqsContentBox(
                question: 'Aspirin belongs to the group of?',
                option1: 'Derived from the animal',
                option2: 'Derived from bacteria',
                option3: 'Synthetic drugs',
                option4: 'Derived from plants',
                option5: 'None of these',
                correctOption: 'd',
              ),
              McqsContentBox(
                question: 'A material which contain weakened pathogen is called?',
                option1: 'Antibiotics',
                option2: 'Vaccines',
                option3: 'Antigens',
                option4: 'Antibodies',
                option5: 'None of these',
                correctOption: 'b',
              ),
              McqsContentBox(
                question: 'he methods of administering vaccines is/are?',
                option1: 'Mouth',
                option2: 'Nasal spray',
                option3: 'Injection',
                option4: 'All of these',
                option5: 'None of these',
                correctOption: 'd',
              ),
              McqsContentBox(
                question: 'Which drug is obtained from minerals?',
                option1: 'Aspirin',
                option2: 'Morphine',
                option3: 'Tincher Lodine',
                option4: 'Antitoxins',
                option5: 'None of these',
                correctOption: 'c',
              ),
              McqsContentBox(
                question: 'Antibiotics kill or stop growth of?',
                option1: 'Worms',
                option2: 'Yeast',
                option3: 'Bacteria',
                option4: 'Viruses',
                option5: 'None of these',
                correctOption: 'c',
              ),
              McqsContentBox(
                question: 'Study of composition and medical application of drugs is called?',
                option1: 'Physiology',
                option2: 'Mycology',
                option3: 'Biotechnology',
                option4: 'Pharmacology',
                option5: 'None of these',
                correctOption: 'd',
              ),
              McqsContentBox(
                question: 'A cardiotonic digitalis is obtained from a plant?',
                option1: 'Mycology',
                option2: 'Cannabis',
                option3: 'Fungi',
                option4: 'Poppy',
                option5: 'None of these',
                correctOption: 'e',
              ),
              McqsContentBox(
                question: 'How much amount of sunlight reaches up to earth and absorbed?',
                option1: '50%',
                option2: '32%',
                option3: '26%',
                option4: '46%',
                option5: 'None of these',
                correctOption: 'a',
              ),
              McqsContentBox(
                question: 'Which is the major effect of global warming?',
                option1: 'Rise in sea level',
                option2: 'Increase in temperature',
                option3: 'Melting of glaciers',
                option4: 'All of them',
                option5: 'None of these',
                correctOption: 'd',
              ),
              McqsContentBox(
                question: 'Higher concentration of CO causes?',
                option1: 'Fatique',
                option2: 'Headache',
                option3: 'Both of them',
                option4: 'Increase in temperature',
                option5: 'None of these',
                correctOption: 'c',
              ),
              McqsContentBox(
                question: 'What percentage of nitrogen and oxygen is in the atmosphere?',
                option1: '89%',
                option2: '69%',
                option3: '79%',
                option4: '9%',
                option5: 'None of these',
                correctOption: 'd',
              ),
              McqsContentBox(
                question: 'The percentage by volume of nitrogen in dry gas is?',
                option1: '20.94%',
                option2: '0.93%',
                option3: '78.09%',
                option4: '0.03%',
                option5: 'None of these',
                correctOption: 'c',
              ),
              McqsContentBox(
                question: 'The layer above troposphere extend upto 50 kilometers called?',
                option1: 'Thermosphere',
                option2: 'Mesosphere',
                option3: 'Hydrosphere',
                option4: 'Stratosphere',
                option5: 'None of these',
                correctOption: 'd',
              ),
              McqsContentBox(
                question: 'The smell of photocopies machine is due to the presence of?',
                option1: 'Chlorine gas',
                option2: 'Ozone gas',
                option3: 'Neon gas',
                option4: 'Helium gas',
                option5: 'None of these',
                correctOption: 'b',
              ),
              McqsContentBox(
                question: 'Building and Monuments lose their beauty and shine due to?',
                option1: 'IR radiations',
                option2: 'Acid rain',
                option3: 'U. V radiations',
                option4: 'Chloroform carbons',
                option5: 'None of these',
                correctOption: 'b',
              ),
              McqsContentBox(
                question: 'Ozone layer is not found is?',
                option1: 'Lower stratosphere',
                option2: 'Upper stratosphere',
                option3: 'Mid stratosphere',
                option4: 'All of them',
                option5: 'None of these',
                correctOption: 'a',
              ),
              McqsContentBox(
                question: '99% of atmosphere consists of?',
                option1: 'O2and CO2',
                option2: 'N2and CO2',
                option3: 'N2 and H2',
                option4: 'N2and O2',
                option5: 'None of these',
                correctOption: 'd',
              ),
              McqsContentBox(
                question: 'A pollutant is a waste material that pollutes?',
                option1: 'Soil',
                option2: 'Air',
                option3: 'Water',
                option4: 'All of them',
                option5: 'None of these',
                correctOption: 'd',
              ),
              McqsContentBox(
                question: 'On which base atmosphere is divided into four regions?',
                option1: 'Change in volume',
                option2: 'Change in temperature',
                option3: 'Change in radiation',
                option4: 'Change in pressure',
                option5: 'None of these',
                correctOption: 'b',
              ),
              McqsContentBox(
                question: 'How many atmospheric temperatures increase every year due to accumulation of CO2 in air?',
                option1: '0.03 oC',
                option2: '2oC',
                option3: '0.05 oC',
                option4: '1oC',
                option5: 'None of these',
                correctOption: 'c',
              ),
              McqsContentBox(
                question: 'Carbon monoxide is harmful to us because?',
                option1: 'It damages lungs tissues',
                option2: 'It makes the blood coagulate',
                option3: 'It paralyses the lungs',
                option4: 'It reduces oxygen carrying ability of hemoglobin',
                option5: 'None of these',
                correctOption: 'd',
              ),
            ],
          ),
        ),
      ),
    );
  }
}


