import 'package:qs_app/question.dart';

class QuizBrain {
  int _questionNumber = 0;
  int noOfCorrectAnswers = 0;

  List<Question> _questionBank = [
    Question('1: The Sum of First 70 even Numbers is  4970', true),
    Question('2: The word Geometry has been derived from two Greek words: Earth measurement', true),
    Question('3: The Sum of First 70 Odd Numbers is 4900', true),
    Question('4: Express 1.09 in term of Percentage 109%', true),
    Question('5: Average of 1,2,3,4,5 is 3', true),
    Question('6: Missing Number in the series 1, 6, 13, 22, 33is 48', false),
    Question('7: One Gross is equal to 10 dozen', false),
    Question('8: A jogger running at 9 kmph alongside a railway track in 240 metres ahead of the engine of a 120 metres long train running at 45 kmph in the same direction. In how much time will the train pass the joɡɡer: 36 sec', true),
    Question('9: Three flags each of different colours are available for a military exercise, Using these flags different codes can be generated by waving I. Single flag of different colours II. Any two and three flags in a different sequence of colours.The maximum number of codes that can be generated is: 15', true),
    Question('10: Two trains are moving in opposite directions 60 km/hr and 90 km/hr. Their lengths are 1.10 km and 0.9 km respectively. The time taken by the slower train to cross the faster train in seconds is 48', true),
    Question('11: Twelve inches equal to how many centimeters 30.48', true),
    Question('12: Father of Calculus Al-Khwarizmi ', true),
    Question('13: 1 inch is equal to 2.4cm', false),
    Question('14: If the average marks of three batches of 55, 60 and 45 students respectively is 50, 55, 60, then the average marks of all the students is 60', false),
    Question('15: If a car is sold for Rs..50000 the profit is 17 percent, what would be profit percentage if sold for Rs. 47000 is 14.4%', false),


  ];

  void nextQuestion() {
    if (_questionNumber < _questionBank.length) {
      _questionNumber++;
    }
  }

  String getQuestionText() {
    return _questionBank[_questionNumber].questionText;
  }

  bool getCorrectAnswer() {
    return _questionBank[_questionNumber].questionAnswer;
  }


  bool isFinished() {
    if (_questionNumber >= _questionBank.length - 1) {

      print('Now returning true');
      return true;

    } else {
      return false;
    }
  }


  void reset() {
    _questionNumber = 0;
    noOfCorrectAnswers = 0;
  }
}
